openapi: 3.0.1
info:
  title: Criteo API
  description: Criteo API - RetailMedia
  version: 2026-01
servers:
- url: https://api.criteo.com
paths:
  /2026-01/retail-media/account-management/accounts/{accountId}/brands/add:
    post:
      tags:
      - Accounts
      description: Add brands to an account
      operationId: AddBrands
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Add Brands
  /2026-01/retail-media/account-management/accounts/{accountId}/brands/remove:
    post:
      tags:
      - Accounts
      description: Remove brands from an account
      operationId: RemoveBrands
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Remove Brands
  /2026-01/retail-media/account-management/accounts/{accountId}/create-brand-account:
    post:
      tags:
      - Accounts
      description: Creates a new child Demand Brand account for the provided parent Private Market account
      operationId: CreatePrivateMarketDemandBrandAccount
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Create Private Market Demand Brand Account
  /2026-01/retail-media/account-management/accounts/{accountId}/create-seller-account:
    post:
      tags:
      - Accounts
      description: Creates a new child Demand Seller account for the provided parent Private Market account
      operationId: CreatePrivateMarketDemandSellerAccount
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Create Private Market Demand Seller Account
  /2026-01/retail-media/account-management/accounts/{accountId}/private-market-child-accounts:
    get:
      tags:
      - Accounts
      description: Gets Private Market child accounts that are associated with the given account
      operationId: GetPrivateMarketChildAccountsByAccountId
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: Get Private Market Child Accounts By Account ID
  /2026-01/retail-media/account-management/accounts/{accountId}/sellers:
    put:
      tags:
      - Accounts
      description: Replace the sellers associated with an account
      operationId: UpdateSellers
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Update Sellers
  /2026-01/retail-media/accounts:
    get:
      tags:
      - Accounts
      description: Gets page of account objects that the current user can access
      operationId: GetAccounts
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: Get Accounts
  /2026-01/retail-media/accounts/{account-id}/audience-segments:
    patch:
      tags:
      - Audience
      description: Updates the properties of all segments with a valid configuration, and returns the full segments. For those that cannot be updated, one or multiple errors are returned.
      operationId: bulkUpdateAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: Bulk Update Audience Segments
  /2026-01/retail-media/accounts/{account-id}/audience-segments/{audience-segment-id}/contact-list:
    get:
      tags:
      - Audience
      description: Returns the statistics of a contact list segment.
      operationId: getAudienceSegmentContactListStatistics
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: Get Audience Segment Contact List Statistics
  /2026-01/retail-media/accounts/{account-id}/audience-segments/create:
    post:
      tags:
      - Audience
      description: Creates all segments with a valid configuration, and returns the full segments. For those that cannot be created, one or multiple errors are returned.
      operationId: bulkCreateAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: Bulk Create Audience Segments
  /2026-01/retail-media/accounts/{account-id}/audience-segments/delete:
    post:
      tags:
      - Audience
      description: Delete the segments associated to the given IDs.
      operationId: bulkDeleteAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: Bulk Delete Audience Segments
  /2026-01/retail-media/accounts/{account-id}/audience-segments/search:
    post:
      tags:
      - Audience
      description: Returns a list of segments that match the provided filters. If present, the filters are AND'ed together when applied.
      operationId: searchAudienceSegments
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: Search Audience Segments
  /2026-01/retail-media/accounts/{account-id}/audiences/search:
    post:
      tags:
      - Audience
      description: Returns a list of audiences that match the provided filters. If present, the filters are AND'ed together when applied.
      operationId: searchAudiences
      security:
      - oauth:
        - RetailMedia_Audience_Read
      summary: Search Audiences
  /2026-01/retail-media/accounts/{account-id}/balances:
    get:
      tags:
      - Balance
      description: Gets page of balance objects for the given account id
      operationId: GetBalancesByAccountId
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: Get Balances By Account ID
    post:
      tags:
      - Balance
      description: Create balance for the given account id
      operationId: CreateBalanceByAccountId
      security:
      - oauth:
        - RetailMedia_Balance_Manage
      summary: Create Balance By Account ID
  /2026-01/retail-media/accounts/{account-id}/balances/{balance-id}:
    get:
      tags:
      - Balance
      description: Get a balance for the given account id and balance id
      operationId: GetBalanceByAccountAndBalanceId
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: Get Balance By Account And Balance ID
    patch:
      tags:
      - Balance
      description: Modify a balance for the given account id
      operationId: ModifyBalanceByAccountAndBalanceId
      security:
      - oauth:
        - RetailMedia_Balance_Manage
      summary: Modify Balance By Account And Balance ID
  /2026-01/retail-media/accounts/{account-id}/balances/{balance-id}/add-funds:
    post:
      tags:
      - Balance
      description: Add funds to a balance for the given account id
      operationId: AddFundsByAccountAndBalanceId
      security:
      - oauth:
        - RetailMedia_Balance_Manage
      summary: Add Funds By Account And Balance ID
  /2026-01/retail-media/accounts/{account-id}/balances/{balance-id}/change-dates:
    post:
      tags:
      - Balance
      description: Change dates of a balance for the given account id
      operationId: ChangeDatesByAccountAndBalanceId
      security:
      - oauth:
        - RetailMedia_Balance_Manage
      summary: Change Dates By Account And Balance ID
  /2026-01/retail-media/accounts/{account-id}/campaigns:
    get:
      tags:
      - Campaign
      description: Gets page of campaign objects for the given account id
      operationId: GetCampaignsByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Campaigns By Account ID
    post:
      tags:
      - Campaign
      description: Creates a new campaign with the specified settings
      operationId: CreateCampaignsByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Campaigns By Account ID
  /2026-01/retail-media/accounts/{account-id}/creatives:
    get:
      tags:
      - Campaign
      description: Get account creatives
      operationId: GetAccountCreatives
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Account Creatives
    post:
      tags:
      - Campaign
      description: Create a creative for an account
      operationId: CreateCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Creative
  /2026-01/retail-media/accounts/{account-id}/creatives/{creative-id}:
    get:
      tags:
      - Campaign
      description: Get the specified creative
      operationId: GetCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Creative
    put:
      tags:
      - Campaign
      description: Update a creative
      operationId: UpdateCreative
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Creative
  /2026-01/retail-media/accounts/{account-id}/creatives/search:
    post:
      tags:
      - Campaign
      description: Get account creatives
      operationId: SearchAccountCreatives
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Search Account Creatives
  /2026-01/retail-media/accounts/{account-id}/keywords/in-review-report:
    get:
      tags:
      - Campaign
      description: Generate a list of reports for line items which contain one or more actionable keyword reviews
      operationId: GetKeywordInReviewReport
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Keyword In Review Report
  /2026-01/retail-media/accounts/{account-id}/line-items:
    get:
      tags:
      - Campaign
      description: Gets page of line item objects for the given account id
      operationId: GetLineItemsByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Line Items By Account ID
  /2026-01/retail-media/accounts/{accountId}/brand-catalog-export:
    post:
      tags:
      - Campaign
      description: Create a request for a Catalog available to the indicated account.
      operationId: CreateBrandCatalogExport
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Brand Catalog Export
  /2026-01/retail-media/accounts/{accountId}/brands:
    get:
      tags:
      - Campaign
      description: Gets page of retailer objects that are associated with the given account
      operationId: GetBrandsByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Brands By Account ID
  /2026-01/retail-media/accounts/{accountId}/catalogs:
    post:
      tags:
      - Campaign
      description: Create a request for a Catalog available to the indicated account.
      operationId: CatalogApi_PostApiV1ExternalAccountCatalogsByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Catalog Post V 1 External Account Catalogs By Account ID
  /2026-01/retail-media/accounts/{accountId}/catalogs/sellers:
    post:
      tags:
      - Campaign
      description: Create a request for a Catalog available to the indicated account.
      operationId: Catalog_PostApiExternalV1AccountCatalogsSellersByAccountId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Catalog Post External V 1 Account Catalogs Sellers By Account ID
  /2026-01/retail-media/accounts/{accountId}/grant-consent:
    post:
      tags:
      - Accounts
      summary: Grant Consent
      description: Grant consent to a business application on behalf of a Private Market demand account
      operationId: GrantConsent
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
  /2026-01/retail-media/accounts/{accountId}/retailers/search:
    post:
      tags:
      - Campaign
      description: Searches for retailers associated with the specified account based on provided search criteria
      operationId: SearchAccountRetailers
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Search Account Retailers
  /2026-01/retail-media/accounts/{accountId}/seller-catalog-export:
    post:
      tags:
      - Campaign
      description: Create a request for a Catalog available to the indicated account.
      operationId: CreateSellerCatalogExport
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Seller Catalog Export
  /2026-01/retail-media/accounts/fees/search:
    post:
      tags:
      - Accounts
      description: Get fees for provided accounts
      operationId: AccountFeesSearch
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: Account Fees Search
  /2026-01/retail-media/accounts/fees/update:
    post:
      tags:
      - Accounts
      description: Set fees for provided accounts
      operationId: UpdateAccountFees
      security:
      - oauth:
        - RetailMedia_Accounts_Manage
      summary: Update Account Fees
  /2026-01/retail-media/accounts/sellers/search:
    post:
      tags:
      - Accounts
      description: Get the sellers mapped to provided accounts
      operationId: SearchSellers
      security:
      - oauth:
        - RetailMedia_Accounts_Read
      summary: Search Sellers
  /2026-01/retail-media/assets:
    post:
      tags:
      - Campaign
      description: Creates an asset
      operationId: CreateAsset
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Asset
  /2026-01/retail-media/auction-line-items/{lineItemId}:
    get:
      tags:
      - Campaign
      description: Gets a sponsored product line item by its id.
      operationId: GetAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Auction Line Item
    put:
      tags:
      - Campaign
      description: Updates a Sponsored Products Line Item given a line item id and a request.
      operationId: UpdateAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Auction Line Item
  /2026-01/retail-media/audience-segments/{audience-segment-id}/contact-list/add-remove:
    post:
      tags:
      - Audience
      description: Add/remove identifiers to or from a retail-media contact list audience-segment, with external audience segment id.
      operationId: AddRemoveContactListByAudienceSegment
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: Add Remove Contact List By Audience Segment
  /2026-01/retail-media/audience-segments/{audience-segment-id}/contact-list/clear:
    post:
      tags:
      - Audience
      description: Delete all identifiers from a retail-media contact list audience-segment, with external audience segment id.
      operationId: ClearContactListByAudienceSegment
      security:
      - oauth:
        - RetailMedia_Audience_Manage
      summary: Clear Contact List By Audience Segment
  /2026-01/retail-media/balances/{balance-id}/campaigns:
    get:
      tags:
      - Balance
      description: Gets page of campaigns for the given balanceId
      operationId: GetCampaignsByBalanceId
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: Get Campaigns By Balance ID
  /2026-01/retail-media/balances/{balance-id}/campaigns/append:
    post:
      tags:
      - Campaign
      description: appends one or more campaigns to the specified balance
      operationId: AppendCampaignsByBalanceId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Append Campaigns By Balance ID
  /2026-01/retail-media/balances/{balance-id}/campaigns/delete:
    post:
      tags:
      - Campaign
      description: Removes one or more campaigns on the specified balance
      operationId: DeleteCampaignsByBalanceId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Delete Campaigns By Balance ID
  /2026-01/retail-media/balances/{balanceId}/history:
    get:
      tags:
      - Balance
      description: Gets the balance's historical change data.
      operationId: GetBalanceHistory
      security:
      - oauth:
        - RetailMedia_Balance_Read
      summary: Get Balance History
  /2026-01/retail-media/billing/partner-report:
    post:
      tags:
      - Billing
      description: Create a Partner Billing Report request.
      operationId: CreatePartnerBillingReportRequestV1
      security:
      - oauth:
        - RetailMedia_Billing_Read
      summary: Create Partner Billing Report Request V 1
  /2026-01/retail-media/billing/partner-report/{requestId}/output:
    get:
      tags:
      - Billing
      description: Get the output of an existing Partner Billing Report.
      operationId: GetPartnerBillingReportOutputV1
      security:
      - oauth:
        - RetailMedia_Billing_Read
      summary: Get Partner Billing Report Output V 1
  /2026-01/retail-media/billing/partner-report/{requestId}/status:
    get:
      tags:
      - Billing
      description: Get the status of an existing Partner Billing Report.
      operationId: GetPartnerBillingReportStatusV1
      security:
      - oauth:
        - RetailMedia_Billing_Read
      summary: Get Partner Billing Report Status V 1
  /2026-01/retail-media/brands/search:
    post:
      tags:
      - Campaign
      description: Search for brands given a retailer ID and search term.
      operationId: SearchBrands
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Search Brands
  /2026-01/retail-media/campaigns/{campaign-id}/preferred-line-items:
    get:
      tags:
      - Campaign
      description: Gets page of preferred line item objects for the given campaign id
      operationId: GetPreferredLineItemsByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Preferred Line Items By Campaign ID
    post:
      tags:
      - Campaign
      description: Creates a new preferred line item with the specified settings
      operationId: CreatePreferredLineItemByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Preferred Line Item By Campaign ID
  /2026-01/retail-media/campaigns/{campaignId}:
    get:
      tags:
      - Campaign
      description: Gets the campaign for the given campaign id
      operationId: GetCampaignByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Campaign By Campaign ID
    put:
      tags:
      - Campaign
      description: Updates the campaign for the given campaign id
      operationId: UpdateCampaignByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Campaign By Campaign ID
  /2026-01/retail-media/campaigns/{campaignId}/auction-line-items:
    get:
      tags:
      - Campaign
      description: Gets a page of sponsored product line items by campaign id.
      operationId: GetAuctionLineItemsByCampaign
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Auction Line Items By Campaign
    post:
      tags:
      - Campaign
      description: Creates new auction line item with the specified settings
      operationId: CreateAuctionLineItem
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Create Auction Line Item
  /2026-01/retail-media/campaigns/{campaignId}/campaign-budget-overrides:
    get:
      tags:
      - Campaign
      description: Get current campaign budget overrides by given campaign id.
      operationId: GetCampaignBudgetOverrides
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Campaign Budget Overrides
    put:
      tags:
      - Campaign
      description: Update campaign budget overrides by given campaign id and new campaign budget overrides settings.
      operationId: UpdateCampaignBudgetOverrides
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Campaign Budget Overrides
  /2026-01/retail-media/catalogs/{catalogId}/output:
    get:
      tags:
      - Campaign
      description: "Output the indicated catalog. Catalogs are only available for retrieval when their associated status request\r\nis at a Success status.\r\nProduces application/x-json-stream CatalogProduct json objects (first introduced in the 2021-07 version)."
      operationId: GetCatalogOutput
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Catalog Output
  /2026-01/retail-media/catalogs/{catalogId}/status:
    get:
      tags:
      - Campaign
      description: Check the status of a catalog request.
      operationId: GetCatalogStatus
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Catalog Status
  /2026-01/retail-media/categories:
    get:
      tags:
      - Campaign
      description: Endpoint to search categories by text and retailer.
      operationId: CategorySearch_GetApiExternalV1Categories
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Category Search Get External V 1 Categories
  /2026-01/retail-media/categories/{categoryId}:
    get:
      tags:
      - Campaign
      description: Endpoint to search for a specific category by categoryId.
      operationId: GetCategory
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Category
  /2026-01/retail-media/line-items/{externalLineItemId}/keywords/recommended:
    get:
      tags:
      - Campaign
      description: Retrieves a collection of recommended keywords for a line item
      operationId: GetRecommendedKeywords
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Recommended Keywords
  /2026-01/retail-media/line-items/{id}/keywords:
    get:
      tags:
      - Campaign
      description: Fetch keywords associated with the specified line item
      operationId: FetchKeywords
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Fetch Keywords
  /2026-01/retail-media/line-items/{id}/keywords/add-remove:
    post:
      tags:
      - Campaign
      description: Add or Remove keywords from the line item in bulk
      operationId: AddRemoveKeywords
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Add Remove Keywords
  /2026-01/retail-media/line-items/{id}/keywords/set-bid:
    post:
      tags:
      - Campaign
      description: Set bid overrides for associated keywords to the given line item in bulk
      operationId: SetKeywordBids
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Set Keyword Bids
  /2026-01/retail-media/line-items/{line-item-id}:
    get:
      tags:
      - Campaign
      description: Gets the line item for the given line item id
      operationId: GetLineItemsByCampaignId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Line Items By Campaign ID
  /2026-01/retail-media/line-items/{line-item-id}/bid-multipliers:
    get:
      tags:
      - Campaign
      description: Fetch all bid multipliers for a given line item
      operationId: GetBidMultipliersByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Bid Multipliers By Line Item ID
    put:
      tags:
      - Campaign
      description: Updates the bid multipliers for a given line item
      operationId: UpdateBidMultipliersByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Bid Multipliers By Line Item ID
  /2026-01/retail-media/line-items/{line-item-id}/keywords/review:
    post:
      tags:
      - Campaign
      description: Update the status of keyword reviews under a line item
      operationId: UpdateKeywordReviews
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Keyword Reviews
  /2026-01/retail-media/line-items/{line-item-id}/products:
    get:
      tags:
      - Campaign
      description: Retrieve a page of promoted products for a line item
      operationId: FetchPromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Fetch Promoted Products
  /2026-01/retail-media/line-items/{line-item-id}/products/append:
    post:
      tags:
      - Campaign
      description: Append a collection of promoted products to a line item
      operationId: AppendPromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Append Promoted Products
  /2026-01/retail-media/line-items/{line-item-id}/products/delete:
    post:
      tags:
      - Campaign
      description: Remove a collection of promoted products from a line item
      operationId: DeletePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Delete Promoted Products
  /2026-01/retail-media/line-items/{line-item-id}/products/pause:
    post:
      tags:
      - Campaign
      description: Pause a collection of promoted products associated with a line item
      operationId: PausePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Pause Promoted Products
  /2026-01/retail-media/line-items/{line-item-id}/products/unpause:
    post:
      tags:
      - Campaign
      description: Un-pause a collection of promoted products associated with a line item
      operationId: UnpausePromotedProducts
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Unpause Promoted Products
  /2026-01/retail-media/line-items/{lineItemId}/line-item-budget-overrides:
    get:
      tags:
      - Campaign
      description: Gets a collection of monthly and daily budget overrides for the provided line item.
      operationId: GetLineItemBudgetOverrides
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Line Item Budget Overrides
    put:
      tags:
      - Campaign
      description: Update line item budget overrides by given external line item id and new line item budget overrides settings.
      operationId: UpdateLineItemBudgetOverrides
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Line Item Budget Overrides
  /2026-01/retail-media/me:
    get:
      tags:
      - Gateway
      description: Get information about the currently logged application
      operationId: GetCurrentApplication
      security:
      - oauth: []
      summary: Get Current Application
  /2026-01/retail-media/preferred-line-items/{line-item-id}:
    get:
      tags:
      - Campaign
      description: Gets the preferred line item for the given line item id
      operationId: GetPreferredLineItemsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Preferred Line Items By Line Item ID
    put:
      tags:
      - Campaign
      description: Updates the preferred line item for the given line item id
      operationId: UpdatePreferredLineItemByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Update Preferred Line Item By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/add-to-basket:
    get:
      tags:
      - Campaign
      description: This endpoint gets the add to basket target on the specified line item.
      operationId: GetAddToBasketTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Add To Basket Targets By Line Item ID
    put:
      tags:
      - Campaign
      description: This endpoint sets the scope of the add to basket target on the specified line item.
      operationId: PutAddToBasketTargetByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Put Add To Basket Target By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/add-to-basket/append:
    post:
      tags:
      - Campaign
      description: This endpoint appends one or more add to basket ids to targeting on the specified line item.  The resulting state of the add to basket target is returned.
      operationId: AppendAddToBasketTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Append Add To Basket Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/add-to-basket/delete:
    post:
      tags:
      - Campaign
      description: This endpoint removes one or more add to basket ids from targeting on the specified line item.  The resulting state of the add to basket target is returned.
      operationId: DeleteAddToBasketTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Delete Add To Basket Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/audiences:
    get:
      tags:
      - Campaign
      description: This endpoint gets the audience target on the specified line item.
      operationId: GetAudienceTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Audience Targets By Line Item ID
    put:
      tags:
      - Campaign
      description: This endpoint sets the scope of the audience target on the specified line item.
      operationId: PutAudienceTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Put Audience Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/audiences/append:
    post:
      tags:
      - Campaign
      description: This endpoint appends one or more audiences ids to targeting on the specified line item.  The resulting state of the audience target is returned.
      operationId: AppendAudienceTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Append Audience Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/audiences/delete:
    post:
      tags:
      - Campaign
      description: This endpoint removes one or more audiences ids from targeting on the specified line item.  The resulting state of the audience target is returned.
      operationId: DeleteAudienceTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Delete Audience Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/stores:
    get:
      tags:
      - Campaign
      description: This endpoint gets the store target on the specified line item.
      operationId: GetStoreTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Store Targets By Line Item ID
    put:
      tags:
      - Campaign
      description: This endpoint sets the scope of the store target on the specified line item.
      operationId: PutStoreTargetByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Put Store Target By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/stores/append:
    post:
      tags:
      - Campaign
      description: This endpoint appends one or more store ids to targeting on the specified line item.  The resulting state of the store target is returned.
      operationId: AppendStoreTargetsByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Append Store Targets By Line Item ID
  /2026-01/retail-media/preferred-line-items/{line-item-id}/targeting/stores/delete:
    post:
      tags:
      - Campaign
      description: This endpoint removes one or more store ids from targeting on the specified line item.  The resulting state of the store target is returned.
      operationId: DeleteStoreTargetByLineItemId
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Delete Store Target By Line Item ID
  /2026-01/retail-media/reports/{reportId}/output:
    get:
      tags:
      - Analytics
      description: Returns the output of an async report
      operationId: GetAsyncExportOutput
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Get Async Export Output
  /2026-01/retail-media/reports/{reportId}/status:
    get:
      tags:
      - Analytics
      description: Returns the status of an async report
      operationId: GetAsyncExportStatus
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Get Async Export Status
  /2026-01/retail-media/reports/accounts:
    post:
      tags:
      - Analytics
      description: "Returns an asynchronous Accounts Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncAccountsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Accounts Report
  /2026-01/retail-media/reports/campaigns:
    post:
      tags:
      - Analytics
      description: "Return an asynchronous Campaigns Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncCampaignsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Campaigns Report
  /2026-01/retail-media/reports/fillrate:
    post:
      tags:
      - Analytics
      description: "Returns an asynchronous Fill Rate Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncFillRateReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Fill Rate Report
  /2026-01/retail-media/reports/line-items:
    post:
      tags:
      - Analytics
      description: "Returns an asynchronous Line Items Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncLineItemsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Line Items Report
  /2026-01/retail-media/reports/revenue:
    post:
      tags:
      - Analytics
      description: "Returns an asynchronous Revenue Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncRevenueReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Revenue Report
  /2026-01/retail-media/reports/unfilled-placements:
    post:
      tags:
      - Analytics
      description: "Returns an asynchronous Unfilled Placements Report\r\n<br />\r\nThis endpoint is subject to specific rate limits."
      operationId: GenerateAsyncUnfilledPlacementsReport
      security:
      - oauth:
        - RetailMedia_Analytics_Read
      summary: Generate Async Unfilled Placements Report
  /2026-01/retail-media/retailers/{retailer-id}/templates:
    get:
      tags:
      - Campaign
      description: Get retailer creative templates
      operationId: GetRetailerCreativeTemplates
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Retailer Creative Templates
  /2026-01/retail-media/retailers/{retailer-id}/templates/{template-id}:
    get:
      tags:
      - Campaign
      description: Gets the template for the specified retailer id and template id
      operationId: GetCreativeTemplate
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Creative Template
  /2026-01/retail-media/retailers/{retailerId}/categories/search:
    post:
      tags:
      - Campaign
      description: Search a retailer categories by given text substring and category ids.
      operationId: SearchCategory
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Search Category
  /2026-01/retail-media/retailers/{retailerId}/cpc-min-bids:
    post:
      tags:
      - Campaign
      description: Get overall and individual minimum bid amount for given retailer id and sku id list.
      operationId: GetCpcMinBidsBySkuIdsV1
      security:
      - oauth:
        - RetailMedia_Campaign_Manage
      summary: Get CPC Min Bids By SKU IDs V 1
  /2026-01/retail-media/retailers/{retailerId}/pages:
    get:
      tags:
      - Campaign
      description: Get the page types available for the given retailer
      operationId: RetailerApi_GetApi202110ExternalRetailerPagesByRetailerId
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Retailer Get External Retailer Pages By Retailer ID
  /2026-01/retail-media/retailers/{retailerId}/recommend-categories:
    post:
      tags:
      - Campaign
      description: Endpoint to get recommended categories by given retailer id and sku id list.
      operationId: GetRecommendedCategories
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Get Recommended Categories
  /2026-01/retail-media/retailers/{retailerId}/recommend-keywords:
    post:
      tags:
      - Campaign
      description: Recommend keywords by given retailer id and sku ids.
      operationId: RecommendedKeywords
      security:
      - oauth:
        - RetailMedia_Campaign_Read
      summary: Recommended Keywords
  /oauth2/token:
    post:
      tags:
      - Authorization
      description: Creates a token when the supplied client credentials or single use authorization code are valid
      operationId: GetToken
      summary: Get Token
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
security:
- oauth: []
tags:
- name: Accounts
- name: Analytics
- name: Audience
- name: Balance
- name: Billing
- name: Campaign
- name: Gateway
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby
