openapi: 3.0.1
info:
  title: Criteo API
  description: Criteo API - MarketingSolutions
  version: 2025-07
servers:
- url: https://api.criteo.com
paths:
  /2025-07/advertisers/me:
    get:
      tags:
      - Advertiser
      description: Fetch the portfolio of Advertisers for this account
      operationId: ApiPortfolioGet
      security:
      - oauth: []
      summary: Portfolio Get
  /2025-07/audiences/{audience-segment-id}/contactlist:
    delete:
      tags:
      - Audience
      description: Delete all identifiers from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Delete All Identifiers From A Contact List Audience Segment
    patch:
      tags:
      - Audience
      description: Add/remove identifiers to or from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Add Remove Identifiers To Or From A Contact List Audience Segment
  /2025-07/log-level/advertisers/{advertiser-id}/report:
    post:
      tags:
      - Analytics
      description: This Statistics endpoint provides publisher data.
      operationId: GetTransparencyReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: Get Transparency Report
  /2025-07/marketing-solutions/ad-sets:
    patch:
      tags:
      - Campaign
      description: Patch a list of AdSets.
      operationId: PatchAdSetsV24Q3
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Patch Ad Sets V 24 Q 3
    post:
      tags:
      - Campaign
      description: Create the specified ad set
      operationId: CreateAdSetV24Q3
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Create Ad Set V 24 Q 3
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}:
    get:
      tags:
      - Campaign
      description: Get the data for the specified ad set
      operationId: GetAdSetV24Q3
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Get Ad Set V 24 Q 3
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/audience:
    put:
      tags:
      - Campaign
      description: Link or unlink an audience with an ad set
      operationId: updateAdSetAudience
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Update Ad Set Audience
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/category-bids:
    get:
      tags:
      - Campaign
      description: Get the Category Bids for all valid Categories associated to an Ad Set
      operationId: GetCategoryBidList
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Get Category Bid List
    patch:
      tags:
      - Campaign
      description: Patch Category Bids for one or more Categories in a single request. Partial success policy is followed.
      operationId: PatchCategoryBidList
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Patch Category Bid List
  /2025-07/marketing-solutions/ad-sets/{ad-set-id}/display-multipliers:
    get:
      tags:
      - Campaign
      description: Get the Display Multipliers for all valid Categories associated to an Ad Set
      operationId: GetDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Get Display Multipliers
    patch:
      tags:
      - Campaign
      description: Patch Display Multipliers for one or more Categories in a single request. Partial success policy is followed.
      operationId: PatchDisplayMultipliers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Patch Display Multipliers
  /2025-07/marketing-solutions/ad-sets/search:
    post:
      tags:
      - Campaign
      description: Search for ad sets
      operationId: SearchAdSetsV24Q3
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Search Ad Sets V 24 Q 3
  /2025-07/marketing-solutions/ad-sets/start:
    post:
      tags:
      - Campaign
      description: Start the specified list of ad sets
      operationId: StartAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Start Ad Sets
  /2025-07/marketing-solutions/ad-sets/stop:
    post:
      tags:
      - Campaign
      description: Stop the specified list of ad sets
      operationId: StopAdSets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Stop Ad Sets
  /2025-07/marketing-solutions/ads/{id}:
    delete:
      tags:
      - Creative
      description: Delete an Ad
      operationId: DeleteAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Delete Ad
    get:
      tags:
      - Creative
      description: Get an Ad with its id
      operationId: GetAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Ad
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/ads:
    get:
      tags:
      - Creative
      description: Get the list of self-services Ads for a given advertiser
      operationId: GetAdvertiserAds
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Ads
    post:
      tags:
      - Creative
      description: Create an Ad
      operationId: CreateAdvertiserAd
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Create Advertiser Ad
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons:
    get:
      tags:
      - Creative
      description: Get the list of self-services Coupons for a given advertiser
      operationId: GetAdvertiserCoupons
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Coupons
    post:
      tags:
      - Creative
      description: Create a Coupon
      operationId: CreateAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Create Advertiser Coupon
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons-supported-sizes:
    get:
      tags:
      - Creative
      description: Get the list of Coupon supported sizes
      operationId: GetAdvertiserCouponSupportedSizes
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Coupon Supported Sizes
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}:
    delete:
      tags:
      - Creative
      description: Delete a Coupon
      operationId: DeleteAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Delete Advertiser Coupon
    get:
      tags:
      - Creative
      description: Get a Coupon with its id
      operationId: GetAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Coupon
    put:
      tags:
      - Creative
      description: Edit a specific Coupon
      operationId: EditAdvertiserCoupon
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Edit Advertiser Coupon
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/coupons/{id}/preview:
    get:
      tags:
      - Creative
      description: Get the preview of a specific Coupon
      operationId: GetAdvertiserCouponPreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Coupon Preview
  /2025-07/marketing-solutions/advertisers/{advertiser-id}/creatives:
    get:
      tags:
      - Creative
      description: Get the list of self-services Creatives for a given advertiser
      operationId: GetAdvertiserCreatives
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Advertiser Creatives
    post:
      tags:
      - Creative
      description: Create a Creative
      operationId: CreateAdvertiserCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Create Advertiser Creative
  /2025-07/marketing-solutions/audience-segments:
    patch:
      tags:
      - Audience
      description: Updates the properties of all segments with a valid configuration, and returns their IDs. For those that cannot be updated, one or multiple errors are returned.
      operationId: bulkUpdateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Update Audience Segments
  /2025-07/marketing-solutions/audience-segments/{audience-segment-id}/contact-list:
    delete:
      tags:
      - Audience
      description: Delete all identifiers from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Delete All Identifiers From A Contact List Audience Segment
    patch:
      tags:
      - Audience
      description: Add/remove identifiers to or from a contact list audience-segment.
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Add Remove Identifiers To Or From A Contact List Audience Segment
  /2025-07/marketing-solutions/audience-segments/{audience-segment-id}/contact-list/statistics:
    get:
      tags:
      - Audience
      description: Returns the statistics of a contact list segment.
      operationId: getAudienceSegmentContactListStatistics
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: Get Audience Segment Contact List Statistics
  /2025-07/marketing-solutions/audience-segments/compute-sizes:
    post:
      tags:
      - Audience
      description: Gets the size of all segments. An error is returned for those whose size calculation is not supported.
      operationId: computeAudienceSegmentsSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Compute Audience Segments Sizes
  /2025-07/marketing-solutions/audience-segments/create:
    post:
      tags:
      - Audience
      description: Creates all segments with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.
      operationId: bulkCreateAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Create Audience Segments
  /2025-07/marketing-solutions/audience-segments/delete:
    post:
      tags:
      - Audience
      description: Delete the segments associated to the given audience IDs.
      operationId: bulkDeleteAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Delete Audience Segments
  /2025-07/marketing-solutions/audience-segments/estimate-size:
    post:
      tags:
      - Audience
      description: Gets the size estimation of a non existent segment. An error is returned when size calculation is not supported.
      operationId: estimateAudienceSegmentSize
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Estimate Audience Segment Size
  /2025-07/marketing-solutions/audience-segments/in-market-brands:
    get:
      tags:
      - Audience
      description: Returns a list with all available in-market brands that can be used to define an in-market segment.
      operationId: getAudienceSegmentsInMarketBrands
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: Get Audience Segments In Market Brands
  /2025-07/marketing-solutions/audience-segments/in-market-interests:
    get:
      tags:
      - Audience
      description: Returns a list with all available in-market interests that can be used to define an in-market segment. These in-market interests correspond to the Google product taxonomy.
      operationId: getAudienceSegmentsInMarketInterests
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: Get Audience Segments In Market Interests
  /2025-07/marketing-solutions/audience-segments/search:
    post:
      tags:
      - Audience
      description: Returns a list of segments that match the provided filters. If present, the filters are AND'ed together when applied.
      operationId: searchAudienceSegments
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: Search Audience Segments
  /2025-07/marketing-solutions/audiences:
    patch:
      tags:
      - Audience
      description: Updates the properties of all audiences with a valid configuration, and returns their IDs. For those that cannot be updated, one or multiple errors are returned.
      operationId: bulkUpdateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Update Audiences
  /2025-07/marketing-solutions/audiences/compute-sizes:
    post:
      tags:
      - Audience
      description: Gets the size of all audiences. An error is returned for those whose size calculation is not supported.
      operationId: computeAudiencesSizes
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Compute Audiences Sizes
  /2025-07/marketing-solutions/audiences/create:
    post:
      tags:
      - Audience
      description: Creates all audiences with a valid configuration, and returns their IDs. For those that cannot be created, one or multiple errors are returned.
      operationId: bulkCreateAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Create Audiences
  /2025-07/marketing-solutions/audiences/delete:
    post:
      tags:
      - Audience
      description: Deletes the audiences associated to the given audience IDs.
      operationId: bulkDeleteAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Bulk Delete Audiences
  /2025-07/marketing-solutions/audiences/estimate-size:
    post:
      tags:
      - Audience
      description: Gets the size estimation of a non existent audience. An error is returned when size calculation is not supported.
      operationId: estimateAudienceSize
      security:
      - oauth:
        - MarketingSolutions_Audience_Manage
      summary: Estimate Audience Size
  /2025-07/marketing-solutions/audiences/search:
    post:
      tags:
      - Audience
      description: Returns a list of audiences that match the provided filters. If present, the filters are AND'ed together when applied.
      operationId: searchAudiences
      security:
      - oauth:
        - MarketingSolutions_Audience_Read
      summary: Search Audiences
  /2025-07/marketing-solutions/campaigns:
    patch:
      tags:
      - Campaign
      description: Patch a list of Campaigns.
      operationId: PatchCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Patch Campaigns
    post:
      tags:
      - Campaign
      description: Create the specified campaign
      operationId: CreateCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
      summary: Create Campaign
  /2025-07/marketing-solutions/campaigns/{campaign-id}:
    get:
      tags:
      - Campaign
      description: Get the data for the specified campaign
      operationId: GetCampaignV23Q1
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Get Campaign V 23 Q 1
  /2025-07/marketing-solutions/campaigns/search:
    post:
      tags:
      - Campaign
      description: Search for campaigns
      operationId: SearchCampaignsV23Q1
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
      summary: Search Campaigns V 23 Q 1
  /2025-07/marketing-solutions/creatives/{id}:
    delete:
      tags:
      - Creative
      description: Delete a Creative if there are no ads binded to it
      operationId: DeleteCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Delete Creative
    get:
      tags:
      - Creative
      description: Get a Creative with its id
      operationId: GetCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Read
      summary: Get Creative
    put:
      tags:
      - Creative
      description: Edit a specific Creative
      operationId: EditCreative
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Edit Creative
  /2025-07/marketing-solutions/creatives/{id}/preview:
    post:
      tags:
      - Creative
      description: Get the preview of a specific Creative
      operationId: GenerateCreativePreview
      security:
      - oauth:
        - MarketingSolutions_Creative_Manage
      summary: Generate Creative Preview
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers:
    get:
      tags:
      - Campaign
      summary: Get Advertisers
      description: Get the collection of advertisers associated with the user.
      operationId: GetAdvertisers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}:
    get:
      tags:
      - Campaign
      summary: Get Advertiser
      description: Get an advertiser.
      operationId: GetAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/ad-preview:
    get:
      tags:
      - Campaign
      summary: Get Seller Ad Demo
      description: "Get a preview of an HTML ad with products belonging to the provided seller\r\n• <b>advertiserId</b>: Valid crp advertiserId, seller belongs to provided advertiser<br />\r\n• <b>sellerId</b>: Products from given SellerId will fill the ad preview, must be existing crp sellerId<br />\r\n• <b>height</b>: height may be supplied to request a specific ad preview height. Default height: 250<br />\r\n• <b>width</b>: width may be supplied to request a specific ad preview width. Default[...]"
      operationId: GetSellerAdDemo
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/adsets:
    get:
      tags:
      - Campaign
      summary: Get Advertiser Adsets
      description: Get the collection of adsets associated with the advertiserId.
      operationId: GetAdvertiserAdsets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/budgets:
    get:
      tags:
      - Campaign
      summary: Get Budgets By Advertiser
      description: Get CRP budgets for a specific advertiser
      operationId: GetBudgetsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/campaigns:
    get:
      tags:
      - Campaign
      summary: Get Advertiser Campaigns
      description: Get the collection of CRP campaigns associated with the advertiserId.
      operationId: GetAdvertiserCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/seller-campaigns:
    get:
      tags:
      - Campaign
      summary: Get Seller Campaigns By Advertiser
      description: Get CRP seller campaigns for a specific advertiser
      operationId: GetSellerCampaignsByAdvertiser
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/{advertiserId}/sellers:
    post:
      tags:
      - Campaign
      summary: Create Sellers
      description: Create new sellers for an advertiser
      operationId: CreateSellers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/advertisers/preview-limit:
    get:
      tags:
      - Campaign
      summary: Get Advertiser Preview Limits
      description: Get the collection of advertisers preview limits associated with the authorized user.
      operationId: GetAdvertiserPreviewLimits
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/budgets:
    get:
      tags:
      - Campaign
      summary: Get Seller Budgets
      description: "Return a collection of budgets filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned, except those whose endDate is in the past. Returned budgets must satisfy all supplied filter\r\ncriteria if multiple parameters are used.\r\n            \r\n<b>Date filter.</b> Filtering can return only budgets that were active for a\r\ndate range by specifying the startBeforeDate and endAfterDate. Leaving o[...]"
      operationId: GetSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
    patch:
      tags:
      - Campaign
      summary: Update Seller Budgets
      description: "Modify one or more existing active budgets to change their limitations or status.\r\nAll three types of budgets can be modified.\r\n            \r\nThe following constraints apply when modifying an existing budget.\r\n            \r\n• <b>campaignIds</b>: a non-empty subset of the original campaign ids MAY be supplied<br />\r\n• <b>amount</b>: an amount MAY be supplied only if the type is not Uncapped and if supplied it MUST be non-negative<br />\r\n• <b>startDate</b>: a futu[...]"
      operationId: UpdateSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
    post:
      tags:
      - Campaign
      summary: Create Seller Budgets
      description: "Create one or more new budgets to enable spending with the given limitations.\r\nAll three types of budgets can be created this way.\r\n            \r\nThe following constraints apply when creating a new budget.\r\n            \r\n• <b>sellerId</b>: the seller MUST be supplied<br />\r\n• <b>campaignIds</b>: a non-empty array of campaign ids MUST be supplied<br />\r\n• <b>budgetType</b>: a budget type MUST be supplied<br />\r\n• <b>amount</b>: an amount MAY be supplied only if[...]"
      operationId: CreateSellerBudgets
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/budgets/{budgetId}:
    get:
      tags:
      - Campaign
      summary: Get Seller Budget
      description: "Return a budget. For example,\r\n            \r\n    {\r\n        \"id\": \"1759183\",\r\n        \"sellerId\": \"321392\",\r\n        \"campaignIds\": [\r\n            143962\r\n        ],\r\n        \"budgetType\": \"Capped\",\r\n        \"amount\": 1000,\r\n        \"startDate\": \"2021-01-11\",\r\n        \"endDate\": \"2021-01-12\",\r\n        \"spend\": null,\r\n        \"status\": \"Active\"\r\n    }\r\n            \r\nA budget limits the spend of a seller for one or m[...]"
      operationId: GetSellerBudget
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
    patch:
      tags:
      - Campaign
      summary: Update Seller Budget
      description: "Modify an existing active budget to change its limitations or status.\r\nAll three types of budgets can be modified.\r\n            \r\nSee the additional restrictions listed in the PATCH budgets endpoint."
      operationId: UpdateSellerBudget
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns:
    get:
      tags:
      - Campaign
      summary: Get Seller Campaigns
      description: "Return a collection of seller campaigns filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned. Returned sellers must satisfy all supplied filter\r\ncriteria if multiple parameters are used."
      operationId: GetSellerCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
    patch:
      tags:
      - Campaign
      summary: Update Seller Campaigns
      description: "Patching a collection of seller campaigns allows their bids to be modified.\r\nEach bid must be a non-negative value. Setting the bid to zero will make a seller campaign inactive.\r\n            \r\nThe currency used for bids will be the default currency of the campaign."
      operationId: UpdateSellerCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns/{sellerCampaignId}:
    get:
      tags:
      - Campaign
      summary: Get Seller Campaign
      description: "Return details for a seller campaign. For example,\r\n            \r\n    {\r\n        \"id\": \"543210.123456\",\r\n        \"sellerId\": \"543210\",\r\n        \"campaignId\": 123456,\r\n        \"bid\": 1.55,\r\n        \"suspendedSince\": \"2018-07-30T15:15:24.813\",\r\n        \"suspensionReasons\": [\r\n            \"NoMoreBudget\"\r\n        ]\r\n    }\r\n            \r\nAn active seller campaign is one for which the value of <b>suspendedSince</b> is null and\r\nthe <b[...]"
      operationId: GetSellerCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
    patch:
      tags:
      - Campaign
      summary: Update Seller Campaign
      description: "Patching a seller campaign allows the bid to be modified. The bid must be a non-negative value.\r\nSetting the bid to zero will make a seller campaign inactive.\r\n            \r\nThe currency used for bids will be the default currency of the campaign."
      operationId: UpdateSellerCampaign
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/seller-campaigns/{sellerCampaignId}/budgets:
    get:
      tags:
      - Campaign
      summary: Get Budgets By Seller Campaign ID
      description: "Return a collection of budgets for this seller campaign filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned, except those whose endDate is in the past. Returned budgets must satisfy all supplied filter\r\ncriteria if multiple parameters are used.\r\n            \r\nSee the budgets endpoint for additional details."
      operationId: GetBudgetsBySellerCampaignId
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers:
    get:
      tags:
      - Campaign
      summary: Get Sellers
      description: "Return a collection of sellers filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned. Returned sellers must satisfy all supplied filter\r\ncriteria if multiple parameters are used."
      operationId: GetSellers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}:
    get:
      tags:
      - Campaign
      summary: Get Seller
      description: "Return details for the selected seller. For example,\r\n            \r\n    {\r\n        \"id\" : \"123456\"\r\n        \"sellerName\": \"HBogart\",\r\n    }"
      operationId: GetSeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}/budgets:
    get:
      tags:
      - Campaign
      summary: Get Budgets By Seller
      description: "Return a collection of budgets for this seller filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned, except those whose endDate is in the past. Returned budgets must satisfy all supplied filter\r\ncriteria if multiple parameters are used. See the budgets endpoint for additional details."
      operationId: GetBudgetsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/sellers/{sellerId}/seller-campaigns:
    get:
      tags:
      - Campaign
      summary: Get Seller Campaigns By Seller
      description: "Return a collection of seller campaigns for this seller filtered by optional filter parameters.\r\nIf all parameters are omitted the entire collection to which the user has\r\naccess is returned. Returned sellers must satisfy all supplied filter\r\ncriteria if multiple parameters are used. See the seller campaigns endpoint for additional details."
      operationId: GetSellerCampaignsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
    post:
      tags:
      - Campaign
      summary: Create Seller Campaigns By Seller
      description: Associate an existing Seller with an existing Campaign allowing for budget creation
      operationId: CreateSellerCampaignsBySeller
      security:
      - oauth:
        - MarketingSolutions_Campaign_Manage
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/campaigns:
    get:
      tags:
      - Campaign
      summary: Campaigns
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated for _campaigns_. The campaign id appears\r\nin the output as the first column.\r\n            \r\nAggregation can be done by `hour`, `day`, `month`, or `year`. The aggregation\r\ninterval size is controlled by `intervalSize`. The time interval appears in\r\nthe output as the second column.\r\n            \r\n## Metrics\r\n            \r\nThe metrics reported by this endpoint are\r\n            \r\n.  | Met[...]
        \ by zero yields null. The\r\ncurrency is assumed to be the local currency established by the advertiser.\r\n            \r\nThe “row” value is a count of the number of rows in the data array, and can be\r\nused to check the integrity of the data.\r\n            \r\nFurther information on the campaign or seller (e.g. the seller name) can be\r\nobtained from the existing V1 or V2 endpoints using the campaign and/or seller\r\nID values."
      operationId: Campaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/seller-campaigns:
    get:
      tags:
      - Campaign
      summary: Seller Campaigns
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated for _seller campaigns_.The campaign id, seller id, and\r\nseller name appear in the first three columns of the output. These are followed by the interval\r\nsize column.\r\n            \r\nAggregation can be done by `hour`, `day`, `month`, or `year`. The aggregation\r\ninterval size is controlled by `intervalSize`. The remaining columns are metrics.\r\n            \r\n## Metrics\r\n            \r\nThe metr[...]
        \ The first three metrics (impressions, clicks, and cost)\r\nalways appear. The remaining depend on the `clickAttributionPolicy` parameter.\r\n            \r\nThe “data” array contains data rows whose values match the entries in the\r\n“columns” array. Id dimensions are numbers while name and date dimensions are strings. The metrics are JSON objects\r\nwhose type is number. Some of these are natural numbers (e.g. clicks and\r\nimpressions) whereas others are decimal values. A divide by z[...]"
      operationId: SellerCampaigns
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/marketplace-performance-outcomes/stats/sellers:
    get:
      tags:
      - Campaign
      summary: Sellers
      description: "## Dimensions\r\n            \r\nGet performance statistics aggregated for _sellers_. The seller id appears\r\nin the output in the first column and the seller name appears in the second.\r\n            \r\nAggregation can be done by `hour`, `day`, `month`, or `year`. The aggregation\r\ninterval size is controlled by `intervalSize`. The time interval appears in\r\nthe output as the second column.\r\n            \r\n## Metrics\r\n            \r\nThe metrics reported by this en[...]
        \ in the\r\n“columns” array. Id dimensions are numbers while name and date dimensions are strings. The metrics are JSON objects\r\nwhose type is number. Some of these are natural numbers (e.g. clicks and\r\nimpressions) whereas others are decimal values. A divide by zero yields null. The\r\ncurrency is assumed to be the local currency established by the advertiser.\r\n            \r\nThe “row” value is a count of the number of rows in the data array, and can be\r\nused to check the integ[...]"
      operationId: Sellers
      security:
      - oauth:
        - MarketingSolutions_Campaign_Read
  /2025-07/marketing-solutions/me:
    get:
      tags:
      - Gateway
      description: Get information about the currently logged application
      operationId: GetCurrentApplication
      security:
      - oauth: []
      summary: Get Current Application
  /2025-07/placements/report:
    post:
      tags:
      - Analytics
      description: Your ads are placed in different domains (publishers) and environments (websites and apps). Thanks to the placements endpoint, you can analyse the performances for each publisher, comparing displays, clicks and sales generated.
      operationId: GetPlacementsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: Get Placements Report
  /2025-07/statistics/report:
    post:
      tags:
      - Analytics
      description: This Statistics endpoint provides adset related data. It is an upgrade of our previous Statistics endpoint, and includes new metrics and customization capabilities.
      operationId: GetAdsetReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: Get Adset Report
  /2025-07/transactions/report:
    post:
      tags:
      - Analytics
      description: This Transactions endpoint provides transactions id related data.
      operationId: GetTransactionsReport
      security:
      - oauth:
        - MarketingSolutions_Analytics_Read
      summary: Get Transactions Report
  /oauth2/token:
    post:
      tags:
      - OAuth
      security: []
      description: Creates a token when the supplied client credentials are valid
      operationId: ApiV1Oauth2TokenPost
      summary: V 1 OAuth 2 Token Post
components:
  securitySchemes:
    oauth:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
        authorizationCode:
          authorizationUrl: https://api.criteo.com/oauth2
          tokenUrl: https://api.criteo.com/oauth2/token
          scopes: {}
security:
- oauth: []
tags:
- name: Advertiser
- name: Analytics
- name: Audience
- name: Campaign
- name: Creative
- name: Gateway
x-samples-languages:
- java
- python
- php
- csharp
- javascript
- curl
- ruby